[build]
  publish = "public"
  functions = "netlify/functions"

[[headers]]
  for = "/pixel.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
